version: '3'

services:
  traefik:
    container_name: traefik
    image: traefik:v3.0
    command: 
      # - "--log.level=DEBUG"
      # api
      - "--api=true"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      # providers
      - "--providers.file.directory=/FileProvider/"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # entrypoints
      - "--entrypoints.raw.address=:80"
      - "--entrypoints.raw.http.redirections.entryPoint.to=tls"
      - "--entrypoints.raw.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.tls.address=:443"
      # mertrics
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
        # others
      - "--serverstransport.insecureskipverify=true"
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"

    restart: unless-stopped
    networks:
      - mnet
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "host.windows.internal:${windows_host}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/FileProvider/:/FileProvider/:ro
      - ./config/certs/:/certs/:ro
    labels:
      - "traefik.enable=true"
      # middlewares
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=lost:$$apr1$$s0c3kzjm$$nLwpHc5gLp1Xix3KEsjfz0" # 使用 httpasswd 生成密码，注意将 $ 替换成 $$
      # traefik-dashboard
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.docker.lost`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=tls"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.middlewares=gzip@docker,traefik-auth@docker"
      - "traefik.http.routers.traefik-dashboard.service=dashboard@internal"
      # traefik-api
      - "traefik.http.routers.traefik-api.rule=Host(`traefik.docker.lost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-api.entrypoints=tls"
      - "traefik.http.routers.traefik-api.tls=true"
      - "traefik.http.routers.traefik-api.middlewares=gzip@docker,traefik-auth@docker"
      - "traefik.http.routers.traefik-api.service=api@internal"

networks:
  mnet:
    name: mnet
    external: true
