
[tls.options.default]
sniStrict = true
minVersion = "VersionTLS12"
cipherSuites = [
  "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
  "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
  "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
  "TLS_AES_128_GCM_SHA256",
  "TLS_AES_256_GCM_SHA384",
  "TLS_CHACHA20_POLY1305_SHA256",
]

[[tls.certificates]]
certFile = "/certs/_wildcard.docker.lost.pem"
keyFile = "/certs/_wildcard.docker.lost-key.pem"
