version: "3"

services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    env_file:
      - .env
    command: redis-server --requirepass $REDIS_PASSWORD --loglevel warning --appendonly yes
    networks:
      - mnet
    volumes:
      - "redis_data:/data" 
    labels:
      - 'traefik.enable=true'
      - 'traefik.tcp.routers.redis.rule=HostSNI(`redis.docker.lost`)'
      - 'traefik.tcp.routers.redis.entrypoints=tls'
      - 'traefik.tcp.routers.redis.tls=true'
      - "traefik.tcp.routers.redis.tls.passthrough=false"
      - "traefik.tcp.routers.redis.service=redis"
      - "traefik.tcp.services.redis.loadBalancer.server.port=6379"


networks:
  mnet:
    name: mnet
    external: true

volumes:
  redis_data:
    name: redis_data
    
